# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e7277e939cea9337f84dd2704cc8f49cbedd0b867dd512913022cba49788d6715fdeba971ef15657eb2a140154472687d9a10ed499d3168f5fac0bdebb73f7

test:
  secret_key_base: 08470a1498d8d3cc1898eea5ceb2ccc7afe653b7ed51157b0461f6b3541ad513775e745358529586cafc640ec8e9b9d3f1f7bf5261d62a668a1dc69e3f6db583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
